### ISSUE TITLE
Search for "Peaches", returns "Snoop Dogg"

### ISSUE THREAD

**Issue by andrewjtimmons** [mehan/hip-hop-misogyny-stats#2]

**Comment by mehan** [comment]
yeah, there are a few searches where the rapgenius API returns something weird as the first result. for example, a search for 'nas' returns 'nasty freestyle' by t-wayne before it returns any nas songs:

![screen shot 2015-05-18 at 11 09 40 pm](https://cloud.githubusercontent.com/assets/1390212/7708108/9a3afdf4-fe21-11e4-975b-4f7ab229da53.png)

haven't yet figured out how to deal with these edge cases. let me know if you have ideas!

**Comment by andrewjtimmons** [comment]
Interesting.

So I think about it this way. People are using your form to search for a name "Enter the name of a hip-hop artist:".  From that screenshot it appears you just return the first result of their search api.  Instead you could check the name of the artist against the search string to see if it is an exact match.  
If match, return artist,
If no match, go to next artist. 
If no matches after ten artists, return nothing and direct user to artist not found page.

If you wanna get really fancy you could use this gem:
http://www.rubydoc.info/gems/similar_text/0.0.4
"USER_SEARCH_STRING".similar("ARTIST_NAME") 
would output a percentage match.  
You could then set a threshold like 90% or 80% (would have to test to get your preference) and return the best matching name.  
If none of the matches cross a certain threshold then you could just direct to the artist not found page

And if you wanna get super fancy you could store misses and try and retrieve them at a later date.  IE scrape the missing artists based on what people are asking for.  
https://www.tumblr.com/tagged/give-the-people-what-they-want

:)

Rad app tho.  Nice work.

**Comment by mehan** [comment]
whoa! that absolutely sounds like the way to do it. will have to try to implement that in the next version. thanks, timmons! <3

**Comment by andrewjtimmons** [comment]
<3 <3 <3

**Comment by jbobrow** [comment]
Ah yeah. In rappers_controller.rb line 31,32, and 37, we could replace `@song_index[0]` with a now "verified" object from the array. Great post Andrew, and of course great tool Mehan! :)
